version: '3'
services:
  db:
    image: mongo:6
    restart: unless-stopped

  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: db
    depends_on:
     - db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
     - db
