name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install flake8
      run: python -m pip install flake8

    - name: Lint with flake8
      run: flake8

  docker:
    runs-on: ubuntu-latest

    needs: [test]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Log into registry ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push IPS data portal
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ghcr.io/rosswhitfield/ips-data-portal/ipsdataportal:dev
        push: true
